#Project Euler Problem #2
#Each new term in the Fibonacci sequence is #generated by adding the previous two terms. By #starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence #whose values do not exceed four million, find the #sum of the even-valued terms.

#variables
x = 1 
y = 2
z = 0 
fibNums = [x, y]
evenTotal = y

#All the fibbonaci numbers in sequence
#are calculated
while z < 4000000:
  #Calculates the first three numbers of the 
  #fibbonaci sequence 
  if z < 5:
    z = x + y
    x = z
    fibNums.append(z)
    if z == 5:
      y = fibNums[2]
  #Calculates the remaining fibboanci 
  #numbers and adds the even ones together
  else:
    z = x + y 
    x = z
    fibNums.append(z)
    y = fibNums[-2]
    if z % 2 == 0:
      evenTotal += z


#Answer
print(fibNums)
print("The sum of all even fibbonaci numbers are", evenTotal)
